[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [{ access = "read-write", path = "../" }]

[dependencies]
forge-std = "1.9.7"
cartesi-rollups-contracts = "2.0.0"
"@openzeppelin-contracts" = { version = "5.2.0", url = "https://soldeer-revisions.s3.amazonaws.com/@openzeppelin-contracts/5_2_0_11-01-2025_09:30:20_contracts.zip" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options